# /***************************************************************************/
# /*!
#  \author  Konstantinos Menychtas --- kmenycht@cs.rochester.edu
#  \brief  "NEON interface for black-box GPU kernel-level management"
# */
# /***************************************************************************/

ccflags-y               := -Iinclude/neon
obj-$(CONFIG_NEON_FACE) += neon_face.o
